#line 2 "calculadora.yy.c"

#line 4 "calculadora.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[327] =
    {   0,
        0,    0,   87,   85,   83,   77,   67,   68,   63,   65,
       66,   85,   61,   85,   85,   76,   62,   64,    3,   85,
        2,   74,   85,   74,   74,   74,   21,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   81,   82,   83,    0,   71,   80,   76,   78,   79,
       75,   76,    0,    7,    4,    5,    6,    0,   74,   84,
       74,   74,   74,   74,   74,   55,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   14,   74,   74,   74,   74,   74,   74,
       11,   74,   74,   74,   74,   74,   79,   75,    0,    0,

       76,   73,    0,   74,   74,   20,   54,   74,   74,   74,
       74,   53,   74,   74,   74,   74,   74,   74,    1,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   37,   74,
       27,   74,   74,   74,   74,   45,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   25,   74,   74,   44,    0,
       75,   72,   74,   74,   74,   35,   74,   74,   74,   74,
       74,   74,    1,   34,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   23,   74,   74,   74,   74,   74,
       74,   24,   74,   74,   74,   39,   74,   74,   74,   70,
       74,   74,   74,   74,   74,   74,   30,   74,   74,   48,

       74,   74,   29,   74,   74,   74,   74,   74,   74,   74,
       38,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   51,   58,   74,   74,   74,   15,   19,   74,   50,
       74,   74,   74,   69,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   33,   28,   74,   74,   74,   57,
       46,   40,   74,   74,   74,   31,   74,   74,   74,   74,
       74,   74,   42,   60,   74,   74,   74,   74,   56,   74,
       74,   13,   74,   74,   32,   74,   74,   26,   74,   74,
       74,   74,   49,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,    8,   10,   43,   74,   74,   74,

       22,   74,   41,   74,   52,   18,   74,   74,   74,   74,
       16,   74,   17,   74,   59,   74,   12,   74,   74,    9,
       74,   36,   74,   74,   47,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   23,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
        1,   24,    1,    1,    1,    1,   25,   26,   27,   28,

       29,   30,   31,   32,   33,   22,   22,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       22,   22,   47,    1,   48,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[49] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        1,    3,    3,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1
    } ;

static const flex_int16_t yy_base[330] =
    {   0,
        0,    0,  634,  635,   47,  635,  635,  627,  635,  635,
      635,  617,  635,  615,   40,   38,  635,  635,   36,  610,
      609,  624,  624,   49,   55,   56,   59,   54,   64,   58,
       69,   71,   68,   60,   84,   67,   70,   97,   74,  107,
       78,  635,  635,  114,  620,  619,  635,   96,  635,    0,
      104,  114,  128,  635,  635,  635,  635,  121,  620,  635,
      119,  127,  113,  130,  131,  141,  109,  143,  145,  147,
      149,  151,  148,  153,  155,  156,  157,  159,  158,  160,
      165,  170,  164,  152,  169,  154,  171,  173,  175,  174,
      195,  177,  198,  199,  200,  201,    0,  195,  209,  607,

      606,  635,  608,  211,  212,  616,  615,  222,  215,  217,
      219,  614,  223,  225,  224,  226,  228,  230,  244,  231,
      233,  250,  234,  242,  241,  237,  247,  252,  613,  253,
      612,  256,  255,  261,  268,  611,  272,  239,  279,  282,
      283,  284,  285,  287,  288,  610,  290,  289,  609,  596,
      595,  635,  293,  294,  296,  606,  297,  299,  300,  301,
      302,  304,  605,  604,  303,  307,  308,  310,  317,  318,
      323,  325,  312,  315,  603,  335,  324,  327,  339,  342,
      350,  602,  352,  354,  355,  601,  357,  358,  359,  600,
      360,  361,  362,  366,  368,  363,  599,   61,  370,  598,

      372,  367,  597,  377,  371,  386,  373,  374,  378,  369,
      595,  379,  381,  384,  387,  388,  389,  390,  393,  391,
      408,  592,  589,  415,  417,  418,  588,  587,  419,  585,
      421,  425,  427,   65,  428,  430,  432,  429,  433,  434,
      435,  440,  436,  441,  584,  583,  442,  444,  446,  581,
      578,  576,  437,  447,  445,  575,  454,  455,  449,  456,
      448,  460,  574,  573,  464,  465,  469,  476,  572,  481,
      482,  568,  483,  485,  567,  488,  490,  565,  489,  491,
      494,  492,  564,  501,  496,  495,  498,  502,  508,  503,
      511,  505,  509,  504,  563,  562,  561,  507,  510,  512,

      560,  513,  559,  522,  558,  557,  519,  516,  535,  536,
      556,  539,  555,  541,  554,  544,  161,  546,  547,   80,
      550,   72,  552,  553,   66,  635,  594,   63,  597
    } ;

static const flex_int16_t yy_def[330] =
    {   0,
      326,    1,  326,  326,  326,  326,  326,  327,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  328,  326,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  326,  326,  326,  327,  327,  326,  326,  326,  329,
      326,  326,  326,  326,  326,  326,  326,  326,  328,  326,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  329,  326,  326,  326,

      326,  326,  326,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  326,
      326,  326,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,    0,  326,  326,  326
    } ;

static const flex_int16_t yy_nxt[684] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
        4,   13,    4,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   22,   23,   24,   22,   25,   26,   27,   28,
       22,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   22,   40,   22,   41,   42,   43,   44,   49,
       44,   51,   58,   52,   50,   54,   55,   58,   58,   58,
       53,   58,   58,   58,   58,   59,   53,   58,   58,   58,
       58,   58,   58,   58,   58,   58,  234,   58,   71,   64,
      234,   58,   61,   58,   66,   67,   72,   58,   74,   62,
       63,   65,   83,   75,   68,   79,   73,   76,   89,   69,

       58,   77,   84,   80,   70,   78,   93,   81,   85,   88,
       58,   48,   58,   82,   96,   44,   58,   44,   53,   98,
       86,   90,   58,   87,   53,   91,   99,   51,   92,   52,
       58,   94,   99,   58,   58,   95,   53,  102,  100,  103,
      100,  107,   53,  101,   58,  112,   58,  104,   58,  105,
       58,   58,   58,  106,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,  110,  111,   58,   58,  108,
      109,  115,   58,   58,   58,  117,   58,   58,   58,  116,
       58,  113,  118,  120,  114,  119,  121,  122,  124,  126,
      127,  125,  129,  132,  136,  128,  123,  130,   58,  139,

      131,   58,   58,   58,   58,  138,  142,  137,  133,  134,
       98,  135,  140,  144,   58,   58,  141,   99,   58,  150,
       58,  150,   58,   99,  151,   58,   58,   58,   58,   58,
      143,   58,  145,   58,   58,  153,   58,   58,  146,  147,
       58,  148,   58,  149,   58,   58,  155,   58,  154,  160,
       58,  156,  164,   58,  157,   58,   58,  172,   58,   58,
      161,  158,  174,  162,   58,  159,  175,  163,  166,  177,
      165,   58,  167,  168,  163,   58,  173,  180,  176,  182,
      163,  169,   58,  170,  171,   58,   58,   58,   58,  178,
       58,   58,   58,   58,  179,  181,   58,   58,  185,   58,

       58,  183,   58,   58,   58,   58,   58,   58,  184,  189,
       58,   58,  186,   58,  187,   58,  191,  192,   58,  188,
       58,   58,  196,  163,  199,  193,   58,   58,   58,  198,
       58,  190,  202,  195,  194,  201,  197,  200,   58,  203,
      204,  208,   58,  205,  213,   58,  210,  214,  206,  212,
      217,  211,  207,   58,  215,   58,  209,   58,   58,  216,
       58,   58,   58,   58,   58,   58,   58,  218,  220,   58,
       58,   58,   58,   58,   58,   58,   58,   58,  223,  219,
       58,   58,   58,  224,   58,  229,  221,   58,  222,   58,
       58,   58,   58,   58,   58,  227,   58,  226,  225,  228,

      232,  230,  231,  236,  233,  235,  244,  238,  241,  239,
      237,   58,  240,  242,  243,  245,  251,  246,   58,  252,
       58,   58,   58,  247,   58,  250,  248,  253,   58,  249,
       58,   58,   58,   58,  254,   58,   58,   58,   58,   58,
       58,  256,  255,   58,   58,   58,  258,   58,   58,   58,
       58,   58,   58,  257,  263,  261,  264,   58,   58,   58,
      259,  268,  270,   58,  269,  265,  260,   58,   58,  262,
      267,  276,   58,  271,  274,  266,  275,  277,  272,   58,
      273,  280,  278,  279,   58,   58,   58,  282,   58,  285,
      281,   58,   58,   58,   58,   58,  283,   58,   58,   58,

      287,   58,  286,  284,   58,   58,   58,   58,   58,  288,
       58,   58,   58,   58,   58,   58,   58,  290,  291,   58,
      297,  294,   58,  289,  293,   58,  300,  295,  292,  302,
      296,  299,  303,  298,  301,  305,  311,  307,   58,   58,
      304,  306,   58,  308,   58,  312,  313,   58,  309,   58,
       58,  310,  315,   58,  314,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,  316,
       58,   58,  317,  318,  321,   58,   58,   58,   58,   58,
      320,   58,  319,  322,   58,  323,   58,   58,   58,  325,
       58,   58,   58,  324,   45,   58,   45,   97,   58,   97,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
      151,  151,   58,   58,   58,   58,   58,   58,   58,   58,
      152,  101,  101,   58,   46,   46,   60,   58,   57,   56,
       48,   47,   46,  326,    3,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326
    } ;

static const flex_int16_t yy_chk[684] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,   15,
        5,   16,   24,   16,   15,   19,   19,   28,   25,   26,
       16,   30,   27,   34,  198,  328,   16,   29,  234,  325,
       36,   33,   31,   37,   32,  322,  198,   39,   28,   25,
      234,   41,   24,  320,   26,   27,   28,   35,   29,   24,
       24,   25,   33,   30,   27,   32,   28,   31,   37,   27,

       38,   31,   34,   32,   27,   31,   39,   32,   35,   36,
       40,   48,   67,   32,   41,   44,   63,   44,   48,   51,
       35,   38,   61,   35,   48,   38,   51,   52,   38,   52,
       62,   40,   51,   64,   65,   40,   52,   58,   53,   58,
       53,   63,   52,   53,   66,   67,   68,   61,   69,   61,
       70,   73,   71,   62,   72,   84,   74,   86,   75,   76,
       77,   79,   78,   80,  317,   65,   66,   83,   81,   64,
       64,   69,   85,   82,   87,   71,   88,   90,   89,   70,
       92,   68,   71,   73,   68,   72,   74,   75,   76,   78,
       79,   77,   81,   84,   86,   80,   75,   82,   91,   89,

       83,   93,   94,   95,   96,   88,   90,   87,   85,   85,
       98,   85,   89,   92,  104,  105,   89,   98,  109,   99,
      110,   99,  111,   98,   99,  108,  113,  115,  114,  116,
       91,  117,   93,  118,  120,  104,  121,  123,   94,   95,
      126,   95,  138,   96,  125,  124,  108,  119,  105,  114,
      127,  109,  117,  122,  110,  128,  130,  120,  133,  132,
      115,  111,  123,  115,  134,  113,  124,  116,  119,  126,
      118,  135,  119,  119,  121,  137,  122,  130,  125,  133,
      138,  119,  139,  119,  119,  140,  141,  142,  143,  127,
      144,  145,  148,  147,  128,  132,  153,  154,  137,  155,

      157,  134,  158,  159,  160,  161,  165,  162,  135,  143,
      166,  167,  139,  168,  140,  173,  145,  147,  174,  141,
      169,  170,  155,  142,  159,  148,  171,  177,  172,  158,
      178,  144,  162,  154,  153,  161,  157,  160,  176,  165,
      166,  169,  179,  167,  173,  180,  170,  174,  167,  172,
      177,  171,  168,  181,  174,  183,  169,  184,  185,  176,
      187,  188,  189,  191,  192,  193,  196,  178,  180,  194,
      202,  195,  210,  199,  205,  201,  207,  208,  184,  179,
      204,  209,  212,  185,  213,  192,  181,  214,  183,  206,
      215,  216,  217,  218,  220,  189,  219,  188,  187,  191,

      195,  193,  194,  201,  196,  199,  210,  204,  207,  205,
      202,  221,  206,  208,  209,  212,  218,  213,  224,  219,
      225,  226,  229,  214,  231,  217,  215,  220,  232,  216,
      233,  235,  238,  236,  221,  237,  239,  240,  241,  243,
      253,  225,  224,  242,  244,  247,  229,  248,  255,  249,
      254,  261,  259,  226,  236,  233,  237,  257,  258,  260,
      231,  241,  243,  262,  242,  238,  232,  265,  266,  235,
      240,  254,  267,  244,  249,  239,  253,  255,  247,  268,
      248,  259,  257,  258,  270,  271,  273,  261,  274,  266,
      260,  276,  279,  277,  280,  282,  262,  281,  286,  285,

      268,  287,  267,  265,  284,  288,  290,  294,  292,  270,
      298,  289,  293,  299,  291,  300,  302,  273,  274,  308,
      282,  279,  307,  271,  277,  304,  286,  280,  276,  288,
      281,  285,  289,  284,  287,  291,  300,  293,  309,  310,
      290,  292,  312,  294,  314,  302,  304,  316,  298,  318,
      319,  299,  308,  321,  307,  323,  324,  315,  313,  311,
      306,  305,  303,  301,  297,  296,  295,  283,  278,  309,
      275,  272,  310,  312,  318,  269,  264,  263,  256,  252,
      316,  251,  314,  319,  250,  321,  246,  245,  230,  324,
      228,  227,  223,  323,  327,  222,  327,  329,  211,  329,

      203,  200,  197,  190,  186,  182,  175,  164,  163,  156,
      151,  150,  149,  146,  136,  131,  129,  112,  107,  106,
      103,  101,  100,   59,   46,   45,   23,   22,   21,   20,
       14,   12,    8,    3,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[87] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
    0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "calculadora.l"
#line 5 "calculadora.l"
	#include <stdio.h>
	#include <stdlib.h>
	// #include <math.h>

	#include "calculadora.h"
	#include "calculadora.tab.h"
#line 737 "calculadora.yy.c"
#line 14 "calculadora.l"
 /* float exponent */
#line 740 "calculadora.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 19 "calculadora.l"


#line 960 "calculadora.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 327 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 635 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "calculadora.l"
{ } // return 0; }
	YY_BREAK
/* comparison ops, all are a CMP token */ 
case 2:
YY_RULE_SETUP
#line 24 "calculadora.l"
{ yylval.fn = 1; } // return CMP; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 25 "calculadora.l"
{ yylval.fn = 2; } // return CMP; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 26 "calculadora.l"
{ yylval.fn = 3; } // return CMP; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "calculadora.l"
{ yylval.fn = 4; } // return CMP; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "calculadora.l"
{ yylval.fn = 5; } // return CMP; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "calculadora.l"
{ yylval.fn = 6; } // return CMP; }
	YY_BREAK
/* keywords */
case 8:
YY_RULE_SETUP
#line 33 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // } // return ALEATORIO; } 
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 34 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return FIMALGORITMO;  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 35 "calculadora.l"
{ printf("\n\n\nPalavra Reservada -> %s \n", yytext); } // return ALGORITMO; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 36 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return SE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 37 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return FIMENQUANTO;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 38 "calculadora.l"
{ printf("Tipo de Variavel -> %s \n", yytext); } // return INTEIRO; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 39 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return OU;  }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 40 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return SENAO; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 41 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return FIMESCOLHA;  }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 42 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return INTERROMPA;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 43 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return OUTROCASO; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 44 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return TIMER;   }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 45 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return ASC	; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 46 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return E;  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 47 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return FIMFUNCAO;  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 48 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return LEIA;   }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 49 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return PARA;  }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 50 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return VAR;  }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 51 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return RETORNE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 52 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return NAO; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 53 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return INICIO; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 54 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return FALSO;    } 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 55 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return COMPR;  }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 56 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return REPITA;  }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 57 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return MUDACOR;  }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 58 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return FUNCAO;  }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 59 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return FACA;  }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 60 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return CASO;  }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 61 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return PROCEDIMENTO; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 62 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return MOD; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 63 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return FIMSE;   }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 64 "calculadora.l"
{ printf("Tipo de Variavel -> %s \n", yytext); } // return REAL; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 65 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return MINUSC;  }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 66 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return FIMREPITA; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 67 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return ESCOLHA; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 68 "calculadora.l"
{ printf("Tipo de Variavel -> %s \n", yytext); } // return CARACTERE;  }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 69 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return XOU; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 70 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return POS;  }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 71 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return MAIUSC;  }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 72 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return FIMPROCEDIMENTO;  }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 73 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return ENTAO;   }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 74 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return ENQUANTO; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 75 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return VETOR;  }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 76 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return PASSO;  }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 77 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return LIMPATELA; } 
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 78 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return ECO;   }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 79 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return ATE;   }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 80 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return DE;   }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 81 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return FIMPARA;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 82 "calculadora.l"
{ printf("Tipo de Variavel -> %s \n", yytext); } // return LOGICO; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 83 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return PAUSA; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 84 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return VERDADEIRO; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 85 "calculadora.l"
{ printf("Palavra Reservada -> %s \n", yytext); } // return VERDADEIRO; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 88 "calculadora.l"
{printf("Caracter Especial -> %s \n", yytext);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 89 "calculadora.l"
{printf("Caracter Especial -> %s \n", yytext);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 90 "calculadora.l"
{printf("Caracter Especial -> %s \n", yytext);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 91 "calculadora.l"
{printf("Caracter Especial -> %s \n", yytext);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 92 "calculadora.l"
{printf("Caracter Especial -> %s \n", yytext);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 93 "calculadora.l"
{printf("Caracter Especial -> %s \n", yytext);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 94 "calculadora.l"
{printf("Caracter Especial -> %s \n", yytext);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 95 "calculadora.l"
{printf("Caracter Especial -> %s \n", yytext);}
	YY_BREAK
/* debug hack */
case 69:
YY_RULE_SETUP
#line 99 "calculadora.l"
{ debug = atoi(&yytext[5]); 
	            if ( debug == 0 ) 
	            	printf("debug disabled\n");
	            else 
	            	printf("debug set to %d\n", debug);
	        }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 106 "calculadora.l"
{ 
		    printf("[DEBUG] NHASH = %d\n", NHASH);
		    int i = 0;
		    for (i = 0; i < NHASH; i++) {
		    	if ( symtab[i].name != NULL ) {
		    		printf("symtab[%4d] = (%s, %lf, %d, %s)\n", 
		    			i, 
		    			symtab[i].name, 
		    			symtab[i].value, 
		    			(symtab[i].func != NULL ? symtab[i].func->nodetype : 0), 
		    			(symtab[i].syms != NULL ? getsymbols( symtab[i].syms ) : "[]" )
		    			);
		    	} 
		    	// printf("symtab[%4d] = ...\n", i);
		    }
		    printf("===============\n");
		}
	YY_BREAK
/* names */
case 71:
YY_RULE_SETUP
#line 126 "calculadora.l"
{ yylval.s = lookup(yytext); printf("String -> %s \n", yytext) ;} // return NAME; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 128 "calculadora.l"
{ yylval.s = lookup(yytext); printf("Atribuição -> %s \n", yytext) ;} // return NAME; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 130 "calculadora.l"
{ yylval.s = lookup(yytext); printf("Declaração -> %s \n", yytext) ;} // return NAME; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 132 "calculadora.l"
{ yylval.s = lookup(yytext); printf("Literal -> %s \n", yytext) ;} // return NAME; }
	YY_BREAK
case 75:
#line 136 "calculadora.l"
case 76:
YY_RULE_SETUP
#line 136 "calculadora.l"
{ yylval.d = atof(yytext); } // return NUM; }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 138 "calculadora.l"
{ } // return EOL; }
	YY_BREAK
case 78:
#line 141 "calculadora.l"
case 79:
#line 142 "calculadora.l"
case 80:
#line 143 "calculadora.l"
case 81:
#line 144 "calculadora.l"
case 82:
#line 145 "calculadora.l"
case 83:
YY_RULE_SETUP
#line 145 "calculadora.l"
{ /* ignora espacos em branco*/ }
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 147 "calculadora.l"
{ printf("c> "); } /* ignore line continuation */ 
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 149 "calculadora.l"
{ yyerror("Caracter invalido: %c\n", *yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 151 "calculadora.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1466 "calculadora.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 327 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 327 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 326);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 151 "calculadora.l"



